### ISSUE TITLE
Could you please add a release tag

### ISSUE THREAD

**Issue by dominics** [calebtr/vonigo-php#1]
Thanks for the useful library!

We've been using it in production for four months. It'd be great if you could tag a version number, so that we can use a semver reference rather than dev-master. Don't mind if it's less than 1.0.0 - so it needn't imply a stable API necessarily.

It also means we don't have to adjust minimum stability, don't have to define `repositories {}` in composer.json if we want to lock the dependency to a specific commit, and `composer update` doesn't have to talk to Github (just packagist) so is faster.

**Comment by calebtr** [comment]
I agree!

I'm going with 0.2. The rough plan is to use 1.* when I can switch out ext-curl for guzzle, and 2.* if/when Vonigo releases a new version of the API. 

Thanks for the nudge, and I'm glad to hear you are using it.
